import Head from "next/head";
import ThemeToggle from "components/theme-toggle";
import { Editor } from "components/editor";
import Logo, { LogoIcon } from "components/logo";
import { chakra } from "@chakra-ui/react";

export default function Home() {
  const initialCode = `import React from "react"
import { ChakraProvider, Box } from "@chakra-ui/react"
  
  function App(){
    return (
        <ChakraProvider>
            <Box bg="red.300">
                wow
            </Box>
        </ChakraProvider>
    )
  }
  `;

  return (
    <div>
      <Head>
        <title>Chakra Playground</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <chakra.header px="4" py="2">
        <Logo />
        <ThemeToggle />
      </chakra.header>
      <Editor initialCode={initialCode} />
    </div>
  );
}
